// board state
export const ADD_BOARD = 'ADD_BOARD';
export const GET_BOARDS_NAMES = 'GET_BOARDS_NAMES';
export const SET_TITLE = 'SET_TITLE';
export const SET_STAR = 'SET_STAR';
export const SET_DESCRIBTION = 'SET_DESCRIBTION';
export const ADD_LIST = 'ADD_LIST';
export const SET_LIST_TITLE = 'SET_LIST_TITLE';
export const ADD_CARD = 'ADD_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const ADD_LABEL = 'ADD_LABEL';
export const UPDATE_LABEL = 'UPDATE_LABEL';
export const DELETE_LABEL = 'DELETE_LABEL';

// alert state
export const SET_ALERT = 'SET_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

// user state
export const SET_CURRENT_BOARD_ID = 'SET_CURRENT_BOARD_ID';
export const CLEAR_CURRENT_BOARD_ID = 'CLEAR_CURRENT_BOARD_ID';
export const SET_CURRENT_LIST_ID = 'SET_CURRENT_LIST_ID';
export const CLEAR_CURRENT_LIST_ID = 'CLEAR_CURRENT_LIST_ID';
export const SET_RECENT_IDS = 'SET_RECENT_IDS';
export const SET_MODAL = 'SET_MODAL';
export const SET_MODAL_TYPE = 'SET_MODAL_TYPE';
export const SET_OPTIONS_MODAL = 'SET_OPTIONS_MODAL';
export const SET_OPTIONS_MODAL_TYPE = 'SET_OPTIONS_MODAL_TYPE';
export const SET_FAST_EDIT_MODAL_POS = 'SET_FAST_EDIT_MODAL_POS';
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD';
export const CLEAR_CURRENT_CARD = 'CLEAR_CURRENT_CARD';
export const SET_MOUSE_POS = 'SET_MOUSE_POS';
export const TOGGLE_BIG_LABELS = 'TOGGLE_BIG_LABELS';
export const SET_OPTIONS_MODAL_STEP = 'SET_OPTIONS_MODAL_STEP';
export const SET_OPTIONS_MODAL_STEP_TYPE = 'SET_OPTIONS_MODAL_STEP_TYPE';
export const SET_OPTIONS_MODAL_STEP_DATA = 'SET_OPTIONS_MODAL_STEP_DATA';

// 
export const TEST = 'TEST';
